#! /bin/sh
xelatex -shell-escape xepersian.dtx
xelatex -shell-escape xepersian.dtx
xelatex -shell-escape xepersian.dtx
teckit_compile parsidigits.map
teckit_compile parsidigits.map
teckit_compile parsidigits.map
mkdir -p doc/xelatex/xepersian fonts/misc/xetex/fontmapping/xepersian source/xelatex/xepersian tex/xelatex/xepersian xepersian
mv *.def *.sty *.cls  tex/xelatex/xepersian
mv *.dtx *.ins source/xelatex/xepersian
mv *.pdf *.py *.tex README ChangeLog img doc/xelatex/xepersian
mv parsidigits.map parsidigits.tec fonts/misc/xetex/fontmapping/xepersian
zip -r xepersiantds doc/xelatex/xepersian fonts/misc/xetex/fontmapping/xepersian source/xelatex/xepersian tex/xelatex/xepersian
mv xepersiantds.zip xepersian.tds.zip
mv xepersian.tds.zip doc/xelatex/xepersian/*.pdf doc/xelatex/xepersian/*.py doc/xelatex/xepersian/README doc/xelatex/xepersian/ChangeLog doc/xelatex/xepersian/img source/xelatex/xepersian/*.dtx source/xelatex/xepersian/*.ins  xepersian
zip -r xepersian xepersian
rm -r xepersian doc tex source fonts
rm *.aux *.glo *.gls *.hd *.idx *.ilg *.ind *.log *.out *.toc



